use eframe::egui::Key;

pub(crate) fn name_from_key(key: Key) -> Option<&'static str> {
    match key {
        Key::Space => Some("space"),
        Key::A => Some("a"),
        Key::B => Some("b"),
        Key::C => Some("c"),
        Key::D => Some("d"),
        Key::E => Some("e"),
        Key::F => Some("f"),
        Key::G => Some("g"),
        Key::H => Some("h"),
        Key::I => Some("i"),
        Key::J => Some("j"),
        Key::K => Some("k"),
        Key::L => Some("l"),
        Key::M => Some("m"),
        Key::N => Some("n"),
        Key::O => Some("o"),
        Key::P => Some("p"),
        Key::Q => Some("q"),
        Key::R => Some("r"),
        Key::S => Some("s"),
        Key::T => Some("t"),
        Key::U => Some("u"),
        Key::V => Some("v"),
        Key::W => Some("w"),
        Key::X => Some("x"),
        Key::Y => Some("y"),
        Key::Z => Some("z"),
        Key::F1 => Some("f1"),
        Key::F2 => Some("f2"),
        Key::F3 => Some("f3"),
        Key::F4 => Some("f4"),
        Key::F5 => Some("f5"),
        Key::F6 => Some("f6"),
        Key::F7 => Some("f7"),
        Key::F8 => Some("f8"),
        Key::F9 => Some("f9"),
        Key::F10 => Some("f10"),
        Key::F11 => Some("f11"),
        Key::F12 => Some("f12"),
        _ => None,
    }
}

pub(crate) fn key_from_name(name: &str) -> Option<Key> {
    match name {
        "a" => Some(Key::A),
        "b" => Some(Key::B),
        "c" => Some(Key::C),
        "d" => Some(Key::D),
        "e" => Some(Key::E),
        "f" => Some(Key::F),
        "g" => Some(Key::G),
        "h" => Some(Key::H),
        "i" => Some(Key::I),
        "j" => Some(Key::J),
        "k" => Some(Key::K),
        "l" => Some(Key::L),
        "m" => Some(Key::M),
        "n" => Some(Key::N),
        "o" => Some(Key::O),
        "p" => Some(Key::P),
        "q" => Some(Key::Q),
        "r" => Some(Key::R),
        "s" => Some(Key::S),
        "t" => Some(Key::T),
        "u" => Some(Key::U),
        "v" => Some(Key::V),
        "w" => Some(Key::W),
        "x" => Some(Key::X),
        "y" => Some(Key::Y),
        "z" => Some(Key::Z),
        "space" => Some(Key::Space),
        "f1" => Some(Key::F1),
        "f2" => Some(Key::F2),
        "f3" => Some(Key::F3),
        "f4" => Some(Key::F4),
        "f5" => Some(Key::F5),
        "f6" => Some(Key::F6),
        "f7" => Some(Key::F7),
        "f8" => Some(Key::F8),
        "f9" => Some(Key::F9),
        "f10" => Some(Key::F10),
        "f11" => Some(Key::F11),
        "f12" => Some(Key::F12),
        _ => None,
    }
}

pub(crate) const ALL_KEYS: &[Key] = &[
    Key::A,
    Key::B,
    Key::C,
    Key::D,
    Key::E,
    Key::F,
    Key::G,
    Key::H,
    Key::I,
    Key::J,
    Key::K,
    Key::L,
    Key::M,
    Key::N,
    Key::O,
    Key::P,
    Key::Q,
    Key::R,
    Key::S,
    Key::T,
    Key::U,
    Key::V,
    Key::W,
    Key::X,
    Key::Y,
    Key::Z,
    Key::Space,
    Key::F1,
    Key::F2,
    Key::F3,
    Key::F4,
    Key::F5,
    Key::F6,
    Key::F7,
    Key::F8,
    Key::F9,
    Key::F10,
    Key::F11,
    Key::F12,
];
